### ISSUE TITLE
Site refresh suggestions

### ISSUE THREAD

**Issue by jzbz** [decred/dcrtimegui#143]
The dcrtime site has been getting a bit of attention lately since it was used in the Brazilian election, I suggest polishing it a bit to bring it in line with our other properties.

1. Custom logo, similar to how Politeia has its own "P" logo dcrtime could have similar.
2. General site enhancements to get the theme closer to what we have on the Pi site.
3. Optional dark mode.
4. Replace or supplement the info pop up with links to the docs that go further in depth about [what dctime is and how it works](https://docs.decred.org/advanced/dcrtime/).
5. We could also experiment with multilingual docs here if we want since as we've seen, the tool has wide appeal. Having a page in the docs that specifically deals with the GUI timestamping service and explains the concepts in basic terms would be an asset.

**Comment by jzbz** [comment]
I'm also partial to the idea of reusing the header from decred.org so we get a bunch of links to Decred sites in front of the eyeballs that use the time stamping service, right now there isn't even a link to the homepage there.

**Comment by xaur** [comment]
+100 this, our product has seen a major use, and the customer has kindly linked https://timestamp.decred.org/ from their website on 2022-10-26:

https://haddadoficial.com.br/lula-e-haddad-registram-plano-de-governo-em-blockchain-para-evitar-fake-news/

(This seems to be a pretty official website, btw, and the story is linked from a couple news outlets now).

I think it is an opportunity to take and polish the UX for anyone who comes to verify the timestamped documents, the sooner the better.

I went through the steps and documented my UX hiccups in detail:

- External website sends me to https://timestamp.decred.org/ . I open it, first 2 second impression is it's nice and simple.

- I see "Upload file" form by default and get stuck for a second. What do I do? I want to *verify* a hash. The help (i) popup does not help (and I had to click it). It should be called Verify and possibly be a default mode.

- I realize I need to click "Input hash", I click it, page title does not change and is still "Create new hash" (I expected it to change).

- Now I need the hash. They gave me the hash on the source website but I want to obtain it direclty from the PDF I've just read. Turns out it is a simple SHA-256, which is great, but it was my lucky techy guess. There was nothing instructing me that it is a SHA-256 or how I can compute SHA-256 of a file.

- I paste the SHA-256, press Submit, and it worked!

- But what I'm seeing now is not super friendly or self-explaining.

- The (i) popup content has changed, but I'm not aware that it changed because the popup is hidden behind a click.

- After reading the (i) popup I feel a bit better but I still don't know what I need to know.

- First, I want a human timestamp in addition to the Unix timestamp. Knowing *when* the file was timestamped is the key thing to do in dcrtime. (-> #144)

- Second, the UI is not guiding me to my next steps of this verification, or what any of this means. A good start would be to make the tx hash clickable (-> #145) and add text labels explaining how exactly what I am seeing is a good and trustworthy thing.

- Using my tech-fu I figured I need to check [the tx on dcrdata](https://dcrdata.decred.org/tx/21a5c0b90ae27db69b21700fcbb9365116ba2f0d40351a217a22c1593b013188), it worked, but again I have no idea why any numbers on that page is a good thing, or which numbers to look at to get satisfied.

I captured it in such detail as I believe having this flow well-polished could be a big win for us.

On a high level, I suggest two general ideas:

- Eliminate popups. Any hidden UI layers are hard to discover. Put all tips on a single UI layers so that the UX organically flows from top to bottom, step by step.

- Put most important guidance into this GUI and only direct to dcrdocs for additional/technical details, to maximize [user retention during their First-Time User Experience](https://en.wikipedia.org/wiki/First-time_user_experience#User_retention).

A bonus of this is people could take screenshots of completed verification with all details *and* tips explaining the numbers, all fitting a single image, and post these on SM.

A good milestone would be if users could complete their first verification by visiting https://timestamp.decred.org/ , making a few clicks, and checking the tx hash on dcrdata.

Ideally though, the tx info would be pulled from dcrdata and shown right here, to cut cross-site clicking to an absolute minimum of 1. It could be a text blurb that combines the verification result and some education:

> This hash was included in transaction 21a5c0b9... which was mined in Decred block 704,826 on 2022-10-21 18:12:39 UTC. In other words, the document's hash existed 25 days ago or earlier, and this fact is very expensive to destroy now that it's on the blockchain. Click [here](https://dcrdata.decred.org/tx/21a5c0b90ae27db69b21700fcbb9365116ba2f0d40351a217a22c1593b013188) to inspect the transaction on Decred Block Explorer.

**Comment by tiagoalvesdulce** [comment]
Implemented in https://github.com/decred/dcrtimegui/pull/151
