### ISSUE TITLE
Use muliple DCRtime servers 

### ISSUE THREAD

**Issue by degeri** [decred/dcrtimegui#23]
Right now we are using decred.org's API. This is good for now. But for true decentralization we need to support and verify with multiple API end points. For this we should either let the user select an API  or use client side randomness to determine from a list.

Also Lets say user submits a hash to server1. Then for verification the user should use server2 and server3. 

Is this doable ? 

Just something to keep in mind while writing the app. 
This is not a priority right now please add the future tag to this.

**Comment by fernandoabolafio** [comment]
@degeri I think that is not possible to timestamp a file in one server and verify it on another. The reason is that the timestamped file depends on the other files from the same "anchor batch" to calculate the Merkle root and verify that in the blockchain. So, as far as I know, the files aren't independently verifiable in the blockchain.

**Comment by degeri** [comment]
hmm ok.. So whats to stop manipulation ? I feel we are missing something here. 

@marcopeereboom please impart your wisdom on us.

**Comment by degeri** [comment]
Once we have the merkle root,  transaction hash and merkle path we should be able to verify right ?

**Comment by degeri** [comment]
https://matrix.to/#/!VFRvyndKpzcLrVslQD:decred.org/$154532346847299qkrmk:decred.org should be possible. I will do more research into this and suggest how we might do this.

**Comment by fernandoabolafio** [comment]
@degeri just a correction to what I said earlier. The files are indeed independently verifiable in the blockchain as long you have merkle path + merkle root + file hash. 
However, to verify a file **with dcrtime**, we justprovide the file hash because the server can match the file hash with the merkle path and merkle root, since it has recorded all the timestamping history.
So, unless the multiple dcrtime servers are synced, one cannot timestamp a file in a server and verify it in another just by providing the file hash.
What can be done is to verify the file using a standalone tool such as this one: https://github.com/decred/dcrtime/tree/master/cmd/dcrtime_checker.

**Comment by marcopeereboom** [comment]
See https://github.com/decred/dcrtime/issues/24

**Comment by fernandoabolafio** [comment]
@degeri I am closing as I think this issue isn't pertinent anymore. Feel free to re-open it if there is still something you want to cover here.
