### ISSUE TITLE
[redesign] Handle error in digest search

### ISSUE THREAD

**Issue by amassarwi** [decred/dcrtimegui#93]
Currently the app is crashing when searching a random digest, it should show `no results found` or something

![image](https://user-images.githubusercontent.com/10324528/68534531-c450c880-0335-11ea-973d-835a1fd1c758.png)

**Comment by thi4go** [comment]
Hey mate, this stack rebuild screen only opens in development environment. Otherwise, the ErrorBoundary component renders the error correctly. if you want to test it further, you can deactivate this screen by adding `iframe { display: none; }` in css. This will make the dev error screen to not render.

**Comment by amassarwi** [comment]
Opps, I see, closing the issue...
